# Generated by Django 3.2.5 on 2021-07-08 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShopItems',
            new_name='ShopItem',
        ),
    ]
